### ISSUE TITLE
Automate the README generation.

### ISSUE THREAD

**Issue by JuanitoFatas** [fastruby/fast-ruby#16]
- [ ] Add a script to append `[link]` to each idiom like following image.
  
  <img width="359" alt="screenshot 2015-08-07 13 39 09" src="https://cloud.githubusercontent.com/assets/1000669/9129384/b56a3aa0-3d09-11e5-93fb-b8337ded3c2b.png">

**Comment by mateusdeap** [comment]
Closing this for now, but I suppose we can revisit this in the future?
