### ISSUE TITLE
Gemify fast-ruby?

### ISSUE THREAD

**Issue by rubyFeedback** [fastruby/fast-ruby#177]
Would it be possible to gemify fast-ruby and also add contributors?

The idea would be to have a gem that just focuses on "fast ruby" in general, also on rubygems.org, not just on github alone. Not sure if this is wanted but I'll just add this issue here, feel free to proceed how you wish to past this point. :)

**Comment by mPanasiewicz** [comment]
Here you are something similar. Almost the same rules
https://github.com/DamirSvrtan/fasterer

**Comment by ParadoxV5** [comment]
“Fast Ruby” is just an online collection of fast(er) strategies, so I don’t think this makes a good Gem which would rather be expected to provide utility.
There’s https://github.com/DamirSvrtan/fasterer, of course.

**Comment by mateusdeap** [comment]
Yeah. I'll close this issue as I also see this more as a collection of idioms rather that a gem. But it can definitely be discussed wether functionality can or should be added.
