### ISSUE TITLE
Suggestion! Add comment on each example why one method is faster than another

### ISSUE THREAD

**Issue by xjyjp** [fastruby/fast-ruby#45]
Hi, JuanitoFatas. Thank you very much for your repo and I get a lot from it. The benchmarks can show which method is much faster clearly. However, I think if we add some comments to explain why it is much faster than another. How ruby implement the method in the source. I think that it would be much better to help users to understand it. Of course, I would like to help in this process.

**Comment by ixti** [comment]
:+1:
