### ISSUE TITLE
Expand README with Ruby version and AS core.

### ISSUE THREAD

**Issue by JuanitoFatas** [fastruby/fast-ruby#5]
Background #4 

Include the ruby version for the timings in the README. Also maybe expand into some variants using popular core extensions provided by ActiveSupport.

**Comment by kbrock** [comment]
can this be closed now that travis is active?

**Comment by kbrock** [comment]
I think this project is here to show what is faster, not the actual speed.
So running on different hardware across runs is ok as long as people are not comparing the various runs

**Comment by mateusdeap** [comment]
Closing this issue since it has been implemented.
