### ISSUE TITLE
Add an article about hash injection

### ISSUE THREAD

**Issue by gogainda** [fastruby/fast-ruby#6]
http://andycroll.com/ruby/benchmarking-each_with_object-against-inject-when-building-hashes-from-arrays/

**Comment by stereobooster** [comment]
Another article https://samsaffron.com/archive/2017/10/18/fastest-way-to-profile-a-method-in-ruby. Adding it here to not open new issue

**Comment by stereobooster** [comment]
there is also https://rubybench.org/

**Comment by mateusdeap** [comment]
So, as can be seen in the PRs discussion, the difference is very minor, so there isn't much sense in adding this to the README.
